apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "version-checker.labels" . | indent 4 }}
{{- with .Values.serviceAccount.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
  name: {{ include "version-checker.name" . }}
